#!/usr/bin/env bash
# crs-quota-reader · 一键安装/管理脚本
#
# Quick install (curl one-liner):
#   curl -fsSL https://raw.githubusercontent.com/jialechen7/crs-quota-reader/main/manage.sh \
#     -o manage.sh && chmod +x manage.sh && ./manage.sh install
#
# 然后可以反复使用:
#   ./manage.sh {install|start|stop|restart|status|logs|update|uninstall|reload-env}
#
# 强制依赖:claude-relay-service 已安装(pincc.ai/manage.sh 那一路或同 schema 部署)。
# 本脚本从 CRS 的 app/.env 读取 REDIS_* / ENCRYPTION_KEY / TIMEZONE_OFFSET,
# 复制到本服务的 app/.env,确保两边解 hash 一致。

set -euo pipefail

# ── 默认配置(可通过环境变量覆盖) ──────────────────────────────────────────
CRS_DIR="${CRS_DIR:-$HOME/claude-relay-service}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/crs-quota-reader}"
APP_DIR="$INSTALL_DIR/app"
REPO_URL="${REPO_URL:-https://github.com/jialechen7/crs-quota-reader.git}"
PORT="${PORT:-8788}"
PM2_NAME="crs-quota-reader"
LOG_FILE="$INSTALL_DIR/service.log"
PID_FILE="$INSTALL_DIR/service.pid"
STATE_FILE="$INSTALL_DIR/.runner"

c_red()   { printf '\033[31m%s\033[0m' "$*"; }
c_grn()   { printf '\033[32m%s\033[0m' "$*"; }
c_yel()   { printf '\033[33m%s\033[0m' "$*"; }
c_cyan()  { printf '\033[36m%s\033[0m' "$*"; }
info()    { printf '%s %s\n' "$(c_cyan ℹ)" "$*"; }
ok()      { printf '%s %s\n' "$(c_grn ✓)" "$*"; }
warn()    { printf '%s %s\n' "$(c_yel ⚠)" "$*"; }
die()     { printf '%s %s\n' "$(c_red ✗)" "$*" >&2; exit 1; }

# ── helpers ─────────────────────────────────────────────────────────────────
have() { command -v "$1" >/dev/null 2>&1; }

read_env_var() {
  # read_env_var <env_file> <var_name> → echo value (空字符串如果没找到)
  local f="$1" name="$2"
  awk -F= -v key="$name" '
    /^[[:space:]]*#/ { next }
    $1 == key { sub(/^[^=]+=/, ""); print; exit }
  ' "$f" 2>/dev/null || true
}

require_crs() {
  [ -d "$CRS_DIR" ] || die "未发现 CRS 目录:$CRS_DIR(可通过 CRS_DIR=... 覆盖)"
  local crs_env="$CRS_DIR/app/.env"
  [ -f "$crs_env" ] || die "CRS 缺 .env:$crs_env(请先用 https://pincc.ai/manage.sh 安装 CRS 并启动一次)"
  local enc; enc="$(read_env_var "$crs_env" ENCRYPTION_KEY)"
  [ -n "$enc" ] || die "CRS .env 里 ENCRYPTION_KEY 为空,无法对齐 hash"
  ok "CRS 已就绪:$CRS_DIR"
}

write_env() {
  # 从 CRS .env 把以下变量同步过来,缺省值兜底
  local crs_env="$CRS_DIR/app/.env"
  local target="$APP_DIR/.env"

  local rh rp rpw rdb rtls enc tz
  rh="$(read_env_var "$crs_env" REDIS_HOST)";       rh="${rh:-localhost}"
  rp="$(read_env_var "$crs_env" REDIS_PORT)";       rp="${rp:-6379}"
  rpw="$(read_env_var "$crs_env" REDIS_PASSWORD)"
  rdb="$(read_env_var "$crs_env" REDIS_DB)";        rdb="${rdb:-0}"
  rtls="$(read_env_var "$crs_env" REDIS_ENABLE_TLS)"
  enc="$(read_env_var "$crs_env" ENCRYPTION_KEY)"
  tz="$(read_env_var "$crs_env" TIMEZONE_OFFSET)";  tz="${tz:-8}"

  cat > "$target" <<EOF
# Generated by manage.sh on $(date '+%Y-%m-%d %H:%M:%S')
# 同步自 $crs_env;不要手动改这里(会被 reload-env 覆盖),
# 要改就改 CRS 的 .env 后重新跑 ./manage.sh reload-env

REDIS_HOST=$rh
REDIS_PORT=$rp
REDIS_PASSWORD=$rpw
REDIS_DB=$rdb
REDIS_ENABLE_TLS=$rtls

ENCRYPTION_KEY=$enc
TIMEZONE_OFFSET=$tz

PORT=$PORT
ACCESS_LOG=true
EOF
  chmod 600 "$target"
  ok ".env 已生成:$target(权限 600)"
}

clone_or_update_repo() {
  if [ -d "$APP_DIR/.git" ]; then
    info "发现已有仓库,执行 git pull..."
    (cd "$APP_DIR" && git pull --ff-only --quiet) || warn "git pull 失败,继续用当前版本"
  else
    have git || die "需要 git"
    info "克隆 $REPO_URL → $APP_DIR"
    mkdir -p "$INSTALL_DIR"
    git clone --quiet "$REPO_URL" "$APP_DIR"
  fi
  ok "代码就绪:$APP_DIR"
}

install_deps() {
  have node || die "需要 node 18+(未检测到)"
  local v; v="$(node -v | sed 's/^v//;s/\..*//')"
  [ "$v" -ge 18 ] || die "node 版本太老:$(node -v),需要 18+"
  info "安装依赖..."
  (cd "$APP_DIR" && npm install --omit=dev --no-audit --no-fund --silent)
  ok "依赖完成"
}

pick_runner() {
  # 检测要走 pm2 / nohup;持久化到 $STATE_FILE
  if [ -f "$STATE_FILE" ]; then
    cat "$STATE_FILE"; return
  fi
  if have pm2; then
    echo pm2
  else
    echo nohup
  fi
}

remember_runner() {
  mkdir -p "$INSTALL_DIR"
  echo "$1" > "$STATE_FILE"
}

# ── runner: pm2 ─────────────────────────────────────────────────────────────
pm2_start() {
  (cd "$APP_DIR" && pm2 start src/server.js --name "$PM2_NAME" --update-env >/dev/null)
  pm2 save >/dev/null 2>&1 || true
}
pm2_stop()    { pm2 stop "$PM2_NAME" >/dev/null 2>&1 || true; }
pm2_restart() { pm2 restart "$PM2_NAME" --update-env >/dev/null 2>&1; }
pm2_status()  { pm2 list | grep -E "id|$PM2_NAME" || echo "(进程不存在)"; }
pm2_logs()    { pm2 logs "$PM2_NAME" --lines "${1:-100}"; }
pm2_delete()  { pm2 delete "$PM2_NAME" >/dev/null 2>&1 || true; }

# ── runner: nohup ───────────────────────────────────────────────────────────
nohup_start() {
  if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    warn "进程已在运行(pid=$(cat "$PID_FILE")),先 stop"
    return 0
  fi
  (cd "$APP_DIR" && nohup node src/server.js >>"$LOG_FILE" 2>&1 &) >/dev/null 2>&1
  # nohup 的子进程 pid 抓不到,稍等再用 pgrep
  sleep 0.5
  local pid; pid="$(pgrep -f "node $APP_DIR/src/server.js" | head -1 || true)"
  [ -n "$pid" ] && echo "$pid" > "$PID_FILE" && return 0
  die "nohup 起不来,看 $LOG_FILE"
}
nohup_stop() {
  if [ -f "$PID_FILE" ]; then
    local pid; pid="$(cat "$PID_FILE")"
    kill "$pid" 2>/dev/null || true
    sleep 0.3
    kill -9 "$pid" 2>/dev/null || true
    rm -f "$PID_FILE"
  fi
}
nohup_restart() { nohup_stop; nohup_start; }
nohup_status() {
  if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    echo "running (pid=$(cat "$PID_FILE"))"
  else
    echo "stopped"
  fi
}
nohup_logs() {
  [ -f "$LOG_FILE" ] || { echo "(no logs yet)"; return; }
  tail -n "${1:-100}" "$LOG_FILE"
}

# ── 通用入口 ────────────────────────────────────────────────────────────────
runner_call() {
  local action="$1"; shift || true
  local r; r="$(pick_runner)"
  "${r}_${action}" "$@"
}

probe_health() {
  local p="${PORT:-8788}"
  for _ in 1 2 3 4 5; do
    if have curl && curl -fsS --max-time 1 "http://127.0.0.1:$p/v1/health" >/dev/null 2>&1; then
      ok "健康检查通过:http://127.0.0.1:$p/v1/health"
      return 0
    fi
    sleep 0.5
  done
  warn "起来了但 /v1/health 没通,看一下 logs"
  return 1
}

# ── 主流程 ──────────────────────────────────────────────────────────────────
cmd_install() {
  info "前置:验证 claude-relay-service 已安装"
  require_crs
  clone_or_update_repo
  write_env
  install_deps
  local r; r="$(pick_runner)"; remember_runner "$r"
  info "启动方式:$r"
  case "$r" in
    pm2)   pm2_delete; pm2_start ;;
    nohup) nohup_stop;  nohup_start ;;
  esac
  sleep 1
  probe_health || true
  cat <<EOF

$(c_grn '✓ 安装完成')

  📌 Quick test:
       curl -H "Authorization: Bearer <your-cc-key>" \\
            http://127.0.0.1:$PORT/v1/account-quota | jq

  📝 管理命令(在 $INSTALL_DIR/manage.sh 处):
       ./manage.sh start | stop | restart | status | logs | update | uninstall
       ./manage.sh reload-env   # 重新从 CRS .env 同步配置

EOF
}

cmd_start()      { runner_call start;   probe_health || true; }
cmd_stop()       { runner_call stop;    ok "已停"; }
cmd_restart()    { runner_call restart; probe_health || true; }
cmd_status()     { runner_call status; }
cmd_logs()       { runner_call logs "${1:-100}"; }
cmd_update() {
  clone_or_update_repo
  install_deps
  cmd_restart
}
cmd_reload_env() {
  require_crs
  write_env
  cmd_restart
}
cmd_uninstall() {
  warn "即将卸载 $INSTALL_DIR(含 .env / 日志,**不**会动 CRS)"
  read -r -p "确认?[y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]] || { info "已取消"; return; }
  local r; r="$(pick_runner 2>/dev/null || true)"
  case "$r" in
    pm2)   pm2_delete ;;
    nohup) nohup_stop ;;
  esac
  rm -rf "$INSTALL_DIR"
  ok "卸载完成"
}

usage() {
  cat <<'EOF'
crs-quota-reader · 安装/管理脚本

  ./manage.sh install                  全新安装(默认 install dir = $HOME/crs-quota-reader)
  ./manage.sh start | stop | restart   启停
  ./manage.sh status                   状态
  ./manage.sh logs [N]                 看最近 N 行(默认 100)
  ./manage.sh update                   git pull + 装依赖 + 重启
  ./manage.sh reload-env               重新从 CRS .env 同步配置 + 重启
  ./manage.sh uninstall                卸载

环境变量:
  CRS_DIR        CRS 根目录(默认 $HOME/claude-relay-service)
  INSTALL_DIR    本服务安装到哪(默认 $HOME/crs-quota-reader)
  PORT           监听端口(默认 8788)
  REPO_URL       仓库 URL(默认 jialechen7/crs-quota-reader)
EOF
}

# 切到当前 manage.sh 所在目录,如果是从 INSTALL_DIR 跑就让相对路径稳定
SCRIPT_PATH="${BASH_SOURCE[0]:-$0}"
case "${1:-}" in
  install)      cmd_install ;;
  start)        cmd_start ;;
  stop)         cmd_stop ;;
  restart)      cmd_restart ;;
  status)       cmd_status ;;
  logs)         shift; cmd_logs "$@" ;;
  update)       cmd_update ;;
  reload-env)   cmd_reload_env ;;
  uninstall)    cmd_uninstall ;;
  ""|-h|--help|help) usage ;;
  *)            usage; exit 2 ;;
esac
